"$schema" = "./node_modules/wrangler/config-schema.json"
name = "family-budget-app"
pages_build_output_dir = "./dist"
compatibility_date = "2026-04-22"

[[d1_databases]]
binding = "DB"
database_name = "family-budget-app"
database_id = "ad522aa0-3103-4b10-b856-9dfd961a2b9e"
preview_database_id = "ad522aa0-3103-4b10-b856-9dfd961a2b9e"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "RECEIPTS"
bucket_name = "family-budget-app-receipts"
preview_bucket_name = "family-budget-app-receipts"
